server:
  port: 19901

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    root: info
    #com.baomidou.example.mapper: debug
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl