server:
  port: 9901
  shutdown: graceful

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    root: info
    #com.baomidou.example.mapper: debug
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

chainIds: BSC